# PersistentVolumeClaim для postgres-pm
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pm-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# Deployment для postgres-pm
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-pm
spec:
  selector:
    matchLabels:
      app: postgres-pm
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-pm
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          env:
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_PASSWORD
              value: "admin"
            - name: POSTGRES_DB
              value: "new_db3"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pm-pvc
---
# Service для postgres-pm
apiVersion: v1
kind: Service
metadata:
  name: db-pm
spec:
  selector:
    app: postgres-pm
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP